apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-blue
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: tomcat
        role: blue
  selector:
    metadata:
      labels:
        app: tomcat
        role: blue
  spec:
    containers:
    - name: tomcat-container
      image: tomcat:7
      ports:
    - containerPort: 8080
      readinessProbe:
        httpGet:
        path: /
        port: 8080
